### PR TITLE
Xamarin.Forms: fix typo in nuget.config

### PR DESCRIPTION
**Pull request by parhamsaremi**
Change fabulousfx to fabulous-dev.

### CODE REVIEW

**Review by TimLariviere — APPROVED** [review]
Thanks a lot!

**Comment by knocte** [comment]
@TimLariviere please note this PR targetted the stable-net6.0 branch, so the fix should be applied to master too.

**Comment by TimLariviere** [comment]
@knocte That's a good point! Could you open a PR for it please?
I will gladly merge it :)

**Comment by knocte** [comment]
TBH it's hard for me to justify spending more time on this because actually we tried to adopt both Android and iOS XamForm templates from this repo, and both efforts failed:
- iOS because of a known issue (at least filed already by someone else).
- Android because of this: https://github.com/xamarin/Xamarin.Forms/issues/15646

So my team will need to upgrade to Maui instead of having some steps in between 😭 .

**Comment by knocte** [comment]
> @knocte That's a good point! Could you open a PR for it please?

BTW, IMO, changes that should go to more than one branch shouldn't need to be PR'ed twice. The point of having the 1st PR target the stable branch is so that later (after merging it), the maintainer can merge the stable branch into master with just one git command.

**Pull request merged**
